version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - gosec
    - misspell
    - rowserrcheck
    - whitespace
  disable:
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - lll
    - mnd
    - noctx
    - nolintlint
  settings:
    gosec:
      excludes:
        - G204
        - G304
      severity: medium
      confidence: medium
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - all
        path: internal/quotes/quotes\.go
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
      - path: (.+)\.go$
        text: should have a package comment
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
