version: "3"

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BUILD_NAME: passkc

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build the binary
    deps: [deps]
    cmds:
      - go build -v -trimpath -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_NAME}} .
    env:
      CGO_ENABLED: 1

  build-race:
    desc: Build with race detector
    deps: [deps]
    cmds:
      - go build -race -v -trimpath -ldflags "-s -w -X main.version={{.VERSION}}" -o {{.BUILD_NAME}}-race .
    env:
      CGO_ENABLED: 1

  test:
    desc: Run tests
    deps: [deps]
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    deps: [deps]
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test-bench:
    desc: Run benchmarks
    deps: [deps]
    cmds:
      - go test -bench=. -benchmem ./...

  lint:
    desc: Run linters
    cmds:
      - gofmt -l -s .
      - go vet ./...
      - test -z "$(gofmt -l -s .)"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BUILD_NAME}} {{.BUILD_NAME}}-race
      - rm -f coverage.out coverage.html
      - rm -f *.tar.gz *.txt

  install:
    desc: Install the binary
    deps: [build]
    cmds:
      - cp {{.BUILD_NAME}} /usr/local/bin/

  archive:
    desc: Create release archive
    deps: [build]
    cmds:
      - tar -czf {{.BUILD_NAME}}-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz {{.BUILD_NAME}}
      - shasum -a 256 {{.BUILD_NAME}}-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz > {{.BUILD_NAME}}-{{.VERSION}}-{{OS}}-{{ARCH}}.tar.gz.sha256

  demo:
    desc: Run demo commands to showcase Unix philosophy features
    deps: [build]
    cmds:
      - echo "=== Demo Unix Philosophy Features ==="
      - echo ""
      - echo "# Show help"
      - ./{{.BUILD_NAME}} --help
