name: Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag annotation
        run: echo "content=$(git tag --format='%(contents)' -n2 ${{ github.ref }})" >> $GITHUB_OUTPUT
        id: notes

      - name: Check for prerelease
        # NOTE: if tag contains a - is a semver prerelease
        run: echo "flag=$(echo '${{ github.ref }}' | grep '-' && echo '--prerelease' || echo '')" >> $GITHUB_OUTPUT
        id: prerelease

      - name: Get the version
        id: get_version
        run: echo "version=$(echo ${{ github.ref }} | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Create release
        run: gh release create ${{ steps.get_version.outputs.version }} --draft --title ${{ steps.get_version.outputs.version }} ${{ steps.prerelease.outputs.flag }} --notes '${{ steps.notes.outputs.content }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: darwin-amd64
          - os: macos-latest
            arch: darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git describe

      - name: Parse tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.versions.outputs.golang }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: ${{ steps.versions.outputs.task }}

      - name: Install dependencies
        run: task deps

      - name: Run tests
        run: task test

      - name: Build binary
        run: task build
        env:
          VERSION: ${{ needs.create-release.outputs.version }}

      - name: Create archive
        run: task archive
        env:
          VERSION: ${{ needs.create-release.outputs.version }}

      - name: Upload release assets
        run: |
          gh release upload ${{ needs.create-release.outputs.version }} \
            passkc-${{ needs.create-release.outputs.version }}-${{ runner.os }}-${{ runner.arch }}.tar.gz \
            passkc-${{ needs.create-release.outputs.version }}-${{ runner.os }}-${{ runner.arch }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: matrix.os == 'macos-latest' && matrix.arch == 'darwin-amd64'
        run: gh release edit ${{ needs.create-release.outputs.version }} --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
